export { CarrotIllustration, CarrotIcon } from './CarrotIllustration'
export { TomatoIllustration, TomatoIcon } from './TomatoIllustration'
export { RaspberryIllustration, RaspberryIcon } from './RaspberryIllustration'
export { BasilIllustration, BasilIcon } from './BasilIllustration'
export { PotatoIllustration, PotatoIcon } from './PotatoIllustration'
export { OnionIllustration, OnionIcon } from './OnionIllustration'
export { KaleIllustration, KaleIcon } from './KaleIllustration'
export { RadishIllustration, RadishIcon } from './RadishIllustration'
export { FavaBeanIllustration, FavaBeanIcon } from './FavaBeanIllustration'
export { CropGraphic } from './CropGraphic'
