export { CarrotIllustration, CarrotIcon } from './CarrotIllustration'
export { TomatoIllustration, TomatoIcon } from './TomatoIllustration'
export { RaspberryIllustration, RaspberryIcon } from './RaspberryIllustration'
export { BasilIllustration, BasilIcon } from './BasilIllustration'
export { PotatoIllustration, PotatoIcon } from './PotatoIllustration'
export { CropGraphic } from './CropGraphic'
